title: "Max Rodrigo"
description: "Maximiliano Rodrigo Software Engineer currently working on Cloud Architecture, Python and Go."
author: "Maximiliano Rodrigo"
email: "contact@maxrodrigo.com"
url: "https://www.maxrodrigo.com"
logo: "/assets/images/favicon.png"

exclude: [ "script/", "Gemfile", "Gemfile.lock", "LICENSE" ]

collections:
    posts:
      output: true
      permalink: /notes/:title.html
    slides:
      output: true

defaults:
    - scope:
        path: ""
      values:
        layout: "default"
    - scope:
        type: "slides"
      values:
        layout: "slide"
        target: "blank"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
