title: "Max Rodrigo"
description: "Software Engineer, Cloud Architecture, Security Researcher."
author: "Maximiliano Rodrigo"
email: "contact@maxrodrigo.com"
url: "https://www.maxrodrigo.com"
logo: "/assets/images/favicon.png"

exclude: [ "script/", "Gemfile", "Gemfile.lock", "LICENSE" ]

collections:
    posts:
      permalink: /notes/:title.html
    slides:
      output: true

defaults:
    -
      scope:
        path: ""
        type: "pages"
      values:
        layout: "default"
    -
      scope:
        path: ""
        type: "posts"
      values:
        layout: "default/post"

sass:
    style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
