baseURL = "https://www.maxrodrigo.com/"
title = "Max Rodrigo"
theme = "wisdom"

languageCode = "en-us"
enableRobotsTXT = true

googleAnalytics = 'G-D07XMVNLNT'

[params]
  author = "Max Rodrigo"
  description =  "A blog by Max Rodrigo on technology and life."
  latestPostsLimit = 10
  hideReadingTime = true
  hideAuthor = true
  keywords = [ "cyber-security", "programming" ]

[menu]
[[menu.main]]
  identifier = 'home'
  name = '~/'
  url = '/'
  weight = -110
[[menu.main]]
  identifier = 'posts'
  name = 'posts'
  url = '/posts/'
  weight = -100
