#!/bin/sh
set -e

echo 'Building website...'
bundle exec jekyll build -q

# Validate built HTML
echo 'Validating HTML...'
bundle exec htmlproofer --disable-external --check-favicon ./_site

# https://stackoverflow.com/a/16607741/578050
if [[ $(git diff --cached --name-status | grep resume.md) ]]; then
  echo 'New version of resume.md founded.'
  ./script/resume_pdf.sh &&
  git add ./assets/pdf
fi
