name: Build Resume
on:
  push:
    branches: [ master ]
    paths:
      - resume.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install wkhtmltopdf
        run: sudo apt install wkhtmltopdf

      - name: Render HTML to PDF
        run: ./script/build_resume.sh

      - uses: actions/upload-artifact@v2
        with:
          name: resume
          path: '*.pdf'
