name: Build Resume
on:
  push:
    branches: [ master ]
    paths: 
      - resume.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install wkhtmltopdf
        run: sudo apt install wkhtmltopdf
        
      - name: Run Script
        run: echo New Resume.
