name: Render CV into a PDF file.
on:
  push:
    branches: [ master ]
    paths:
      - cv.md
      - assets/css/cv.scss

jobs:
  render-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt install -y build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info ruby-full build-essential zlib1g-dev
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          sudo gem install jekyll bundler

      - name: Build
        run: |
          bundle install
          bundle exec jekyll build

      - name: Setup Weasyprint
        run: |
          python3 -m venv ./venv
          . ./venv/bin/activate
          pip install weasyprint

      - name: Render PDF
        run: |
          . ./venv/bin/activate
          weasyprint ./_site/cv.html Luis_Maximiliano_Rodrigo_Zubieta_CV.pdf

      - uses: actions/upload-artifact@v2
        with:
          name: curriculum-vitae
          path: '*.pdf'
